version: "3.8"

services:
  app:
    build: .
    container_name: crypto-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    dns:
      - 8.8.8.8   # Google DNS
      - 1.1.1.1   # Cloudflare DNS

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
